# Generated by Django 2.1.7 on 2019-02-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='frequency',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
